"use strict";
exports.__esModule = true;
var Carro_1 = require("./Carro");
var Moto_1 = require("./Moto");
var Concessionaria_1 = require("./Concessionaria");
var carro = new Carro_1["default"]('Veloster', 3);
var moto = new Moto_1["default"]();
moto.acelerar();
carro.acelerar();
console.log(carro);
console.log(moto);
var concessionaria = new Concessionaria_1["default"]('', []);
console.log(concessionaria.fornecerHorariosFuncion());
